version: "3.8"
name: coffeedia-infra
services:
  # 쓰기 전용 DB
  coffeedia-postgres-main:
    image: bitnami/postgresql:14
    container_name: coffeedia-postgres-main
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/volumes/main:/bitnami/postgresql"
      - ./postgresql/init.sql:/docker-entrypoint-initdb. d/db.sql
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replicator_user
      POSTGRESQL_REPLICATION_PASSWORD: replicator_password
      POSTGRESQL_USER: user
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: coffeedia_db
    networks:
      - coffeedia-network

  # 읽기 전용 DB
  coffeedia-postgres-replica:
    image: bitnami/postgresql:14
    container_name: coffeedia-postgres-replica
    depends_on:
      - coffeedia-postgres-main
    ports:
      - "5433:5432"
    volumes:
      - "./postgresql/volumes/replica:/bitnami/postgresql"
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replicator_user
      POSTGRESQL_REPLICATION_PASSWORD: replicator_password
      POSTGRESQL_MASTER_HOST: coffeedia-postgres-main
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_USER: user
      POSTGRESQL_PASSWORD: password
    networks:
      - coffeedia-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2.arm64
    container_name: coffeedia-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok"
    volumes:
      - "./zookeeper/volumes/data:/var/lib/zookeeper/data"
      - "./zookeeper/volumes/transactions:/var/lib/zookeeper/log"
    networks:
      - coffeedia-network

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.2.2.arm64
    container_name: coffeedia-kafka-broker-1
    hostname: kafka-broker-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./kafka/volumes/broker-1:/var/lib/kafka/data"
    networks:
      - coffeedia-network

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.2.2.arm64
    container_name: coffeedia-kafka-broker-2
    hostname: kafka-broker-2
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./kafka/volumes/broker-2:/var/lib/kafka/data"
    networks:
      - coffeedia-network

  kafka-broker-3:
    image: confluentinc/cp-kafka:7.2.2.arm64
    container_name: coffeedia-kafka-broker-3
    hostname: kafka-broker-3
    ports:
      - "39092:39092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:9092,EXTERNAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./kafka/volumes/broker-3:/var/lib/kafka/data"
    networks:
      - coffeedia-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: coffeedia-kafka-ui
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - "9000:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
    networks:
      - coffeedia-network

  coffeedia-redis:
    image: redis:7.0
    container_name: coffeedia-redis
    ports:
      - "6379:6379"
    networks:
      - coffeedia-network

networks:
  coffeedia-network:
    driver: bridge
