spring.profiles.active: local

spring:
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    main:
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        connection-timeout: 20000
        idle-timeout: 300000
        pool-name: MainHikariPool

    replica:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 3
        connection-timeout: 20000
        idle-timeout: 300000
        pool-name: ReplicaHikariPool

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s

---
spring.config.activate.on-profile: local

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

  datasource:
    main:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/coffeedia_db
        username: user
        password: password
    replica:
      hikari:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5433/coffeedia_db
        username: user
        password: password

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
